---
name: sleepserver
version: v0.0.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: an http server that sleeps on the job
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=sleepserver
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/sleepserver/trunk
requires:
  HTTP::Server::Simple::CGI: 0
build_requires:
  Module::Build: 0.26
  Test::More: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  sleepserver:
    file: bin/sleepserver
    version: v0.0.1
